### ISSUE TITLE
The bot is offline

### ISSUE THREAD

**Issue by mariosabatino** [mihaip/push-bot#2]
I've tried to add the bot (push-bot-hrd@appspot.com) to my contact list but it seems is not working.

Kind regards
M.

**Comment by mihaip** [comment]
The service relied on the App Engine XMPP API, which was [deprecated in 2016 and removed in 2017](https://cloud.google.com/appengine/docs/admin-api/release-notes#October_27_2016). I've added a notice to the repository and will archive it.
